### ISSUE TITLE
Render or Pause or FixedInBottom = true causes unhandled exception on Linux

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [iluvadev/ConsoleProgressBar#1]
Hi,
I have a console program written in net6.0 and should run on Linux, which I am using WSL2 and Ubuntu 22.04 for this purpose. I need to write on the cosole just like to your [example](https://github.com/iluvadev/ConsoleProgressBar#writing-on-console). However, I also need to intract with user sometimes and get inputs. Therfore, I would like to stop the progress bar and write a message and ask for input. In the following cases I get an exception.

- By initializing the progress bar with FixedInBottom = true
- By calling the Pause
- By calling the Render

here is the exception:
Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.get_CursorVisible()
   at iluvadev.ConsoleProgressBar.ProgressBar.Render()
   at iluvadev.ConsoleProgressBar.ProgressBar.Pause()

**Comment by isaacrlevin** [comment]
FWIW this error happens when using this package at all on Ubuntu. For reference, if I use the base example

```csharp
const int max = 500;

//Create the ProgressBar
using (var pb = new ProgressBar { Maximum = max })
{
  for (int i = 0; i < max; i++)
  {
    Task.Delay(10).Wait(); //Do something
    pb.PerformStep(); //Step in ProgressBar (Default is 1)
  }
}
````

You get this error
> Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.get_CursorVisible()
   at iluvadev.ConsoleProgressBar.ProgressBar.Render()
   at iluvadev.ConsoleProgressBar.ProgressBar.Dispose()

So not sure if there is some issue with 22.04, but it doesn't work with .NET 8 either. Here is my `uname -a` and `dotnet --info`

> Linux MediaServer 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```bash
.NET SDK
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/241/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [/snap/dotnet-sdk/241/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/snap/dotnet-sdk/241/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/snap/dotnet-sdk/241/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
````

Also the console basically is unusable after this error is thrown

**Comment by isaacrlevin** [comment]
Dug a bit more, this is actually a known issue with the .NET Runtime as you cannot consistently set the cursor's visibility in Linux.

https://github.com/dotnet/runtime/issues/31063
